insta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('user.urls')),
    path('', include('post.urls')),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.index, name='index'), # 127.0.0.1:8000 과 views.py 폴더의 index 함수 연결
    path('post/', views.post, name='post'), # 127.0.0.1:8000/post 과 views.py 폴더의 post 함수 연결
    path('post/delete/<int:id>', views.delete_post, name='delete-post'),
    path('post/update/<int:id>', views.update_post, name='update-post'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('signin/',views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/',views.logout, name='logout'),
    

]

post/models.py
from django.db import models
from user.models import User

# Create your models here.
class Post(models.Model):
    class Meta:
        db_table = "post"

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

user/models.py
from django.contrib.auth.models import AbstractUser 
from django.db import models

# Create your models here.
class User(AbstractUser):
    pass

user/forms.py
from django import forms
from .models import User


class SignupForm(forms.ModelForm):

    class Meta:
        model = User 
        fields = ["username"]  
        
    def signup(self, request, user):
        user.username = self.cleaned_data["username"] 
        user.save()

post/views.py
from django.contrib.auth.decorators import login_required
from matplotlib.style import context
from .models import Post
from django.shortcuts import render, redirect


# Create your views here.
def index(request):
    user = request.user.is_authenticated  # 사용자가 인증을 받았는지 (로그인이 되어있는지)
    if user:
        return redirect('/post')
    else:
        return redirect('/account/signin')


def post(request):
    if request.method == 'GET':
        user = request.user.is_authenticated  # 사용자가 인증을 받았는지 (로그인이 되어있는지)
        if user:    # 로그인 한 사용자
            all_post = Post.objects.all().order_by('-created_at')
            return render(request, 'post/index.html', {'post': all_post})
        else:
            return redirect('/account/signin')

    elif request.method == 'POST':  # 요청 방식이 POST 일때
        user = request.user  # 현재 로그인 한 사용자를 불러오기
        my_post = Post()  # 글쓰기 모델 가져오기
        my_post.author = user  # 모델에 사용자 저장
        my_post.content = request.POST.get('my-content', '')  # 모델에 글 저장
        my_post.save()
        return redirect('/post')

# 게시글 삭제
@login_required
def delete_post(request, id):
    my_post = Post.objects.get(id=id)
    my_post.delete()
    return redirect('/post')

@login_required
def update_post(request, id):
    my_post = Post.objects.get(id=id)

    if request.method == "POST":
        my_post.content = request.POST['content']
        my_post.author = request.POST['author']

        post.save()
        return redirect('/post')

    else:
        postForm = Post
        return render(request, 'update.html', {'postForm':postForm})

user/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from .models import User
from django.contrib.auth import get_user_model #사용자가 있는지 검사하는 함수
from django.contrib import auth # 사용자 auth 기능


# Create your views here.
def signup(request):
    if request.method == "GET":
        user = request.user.is_authenticated # 로그인 된 사용자가 요청하는지 검사
        if user: # 로그인이 되어있다면
            return redirect('/')
        else: # 로그인이 되어있지 않다면
            return render(request, 'user/account/signup.html')
            
    elif request.method == "POST":
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        passwordcheck = request.POST.get('passwordcheck')
        if password != passwordcheck:
            # User.objects.create_user(username = username, password = password)
            return redirect('user/account/signup.html') 
        else:
            exist_user = get_user_model().objects.filter(username=username)
            if exist_user:
                return render(request, 'user/account/signup.html') # 사용자가 존재하기 때문에 사용자를 저장하지 않고 회원가입 페이지를 다시 띄움
            else:
                User.objects.create_user(username=username, password=password)
                return redirect('/account/signin') # 회원가입이 완료되었으므로 로그인 페이지로 이동

def signin(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            return redirect('/account/signin')  # 로그인 실패
    elif request.method == 'GET':
        user = request.user.is_authenticated # 로그인 된 사용자가 요청하는지 검사
        if user: # 로그인이 되어있다면
            return redirect('/')
        else: # 로그인이 되어있지 않다면
            return render(request, 'user/account/login.html')

@login_required
def logout(request):
    auth.logout(request) # 인증 되어있는 정보를 없애기
    return redirect("/")

post/templates/post/index.html
{% extends "post_base/base_with_header.html" %}

{% block title %}메인페이지 | Sparkling Coffee Club{% endblock title %}
{% block index-style %}
    <style>
        /* .nounderline {
  text-decoration: none !important
}     */
        .comment_field {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
        }
    </style>
{% endblock index-style %}

{% load static %}

{% block content %}
    <div class="container timeline-container">
        <div class="row">
            <!-- 왼쪽 컬럼 -->
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ user.username }}</h5>
                        <p class="card-text"> {{ user.eamil }}</p>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ user.username }}</h5>
                        <p class="card-text"> {{ user.eamil }}</p>
                    </div>

                </div>
            </div>

            <!-- 오른 쪽 컬럼-->
            <div class="col-md-7">
                <!-- 글을 작성 하는 곳 -->
                <div class="row mb-2">
                    <div class="col-md-12">
                        <!-- nav 때문에 안보이는 부분 보이게 공간넣어둠-->
                        <div class="card">
                            <div class="card-body">
                                <div class="media">
                                    <div class="media-body">
                                        <h5 class="mt-0"></h5>
                                        <p>
                                        <form>
                                            <div class="form-group mb-2">
                                                <button></button>
                                            </div>
                                            
                                        </form>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- post create -->
                        <div class="card">
                            <div class="card-body">
                                <div class="media">
                                    <div class="media-body">
                                        <h5 class="mt-0">나의 이야기를 적어주세요</h5>
                                        <p>
                                        <form action="/post/" method="post">
                                            {% csrf_token %}
                                            <div class="form-group mb-2">
                                                <textarea class="form-control" style="resize: none" name='my-content' id="my-content"></textarea>
                                            </div>
                                            <button type="submit" class="btn btn-primary" style="float:right;">작성하기</button>
                                        </form>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <!-- 작성 된 글이 나오는 곳 -->
                <div class="row">
                    {% for post_ in post %}
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    {% if post_.author == user %}
                                    <div style="text-align: right">
                                        <a href="/post/delete/{{ post_.id }}">
                                            <span class="badge rounded-pill bg-danger">삭제</span>
                                        </a>
                                    </div>
                                    <div style="text-align: right">
                                        <a href="/post/update/{{ post_.id }}">
                                            <span class="badge rounded-pill bg-success">수정</span>
                                        </a>
                                    </div>
                                    {% endif %}
                                    <div class="media">
                                        <div class="media-body">
                                            <h5 class="mt-0">{{ post_.content }}</h5>
                                        </div>
                                        <div style="text-align: right">
                                            <span style="font-size: small">{{ post_.author.username }}-{{ post_.created_at|timesince }} 전</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock %}

post/templates/post/update.html
{% extends "post_base/base_with_header.html" %}

{% block content %}
<div class="row mb-2">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="media">
                    <div class="media-body">
                        {% csrf_token %}
                        <h5 class="mt-0">{{ post_.content }}</h5>
                        <p>
                        <form action="/post/" method="post">
                            
                            <div class="form-group mb-2">
                                <textarea class="form-control" style="resize: none" name='my-content' id="my-content"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary" style="float:right;">수정</button>
                        </form>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

post/templates/post_base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/new_post.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/theme.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'user/favicon/favicon.ico' %}">

    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    {% block index-style %} {% endblock %}

    <title>{% block title %}Sparkling Coffee Club{% endblock title %}</title>

  </head>
  <body>
    {% block header %}{% endblock header %}
    {% block content %}{% endblock content %}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="{% static 'user/js/main.js' %}"></script>
    <script src="{% static 'user/js/new_post.js' %}"></script>

  </body>
</html>

post/templates/post_base/base_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/detail-page.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'user/favicon/favicon.ico' %}">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    {% block post-detail-style %} {% endblock %}
    <title>{% block title %}Sparkling Coffee Club{% endblock title %}</title>
  </head>
  <body>
    {% block header %}{% endblock header %}
    {% block content %}{% endblock content %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'user/js/main.js' %}"></script>
    
</body>
</html>

post/templates/post_base/base_detail_with_header.html
{% extends "post_base/base_detail.html" %}
{% load static %}
{% block post-detail-style %} {% endblock %}
{% block header %}

{% if user.is_authenticated %}
    <section id="container">
        <header id="header">
            <section class="inner">
                <h1 class="logo">
                    <a href="{% url 'index' %}">
                        <div class="sprite_write_logo"></div>
                    </a>
                </h1>
                <form  method="get">
                    <div class="search_box">
                        <input name="query" type="text" placeholder="검색" id="search-field" >
                        <div class="fake_field">
                            <span class="sprite_small_search_icon"></span>
                            <span>검색</span>
                            <button style="display:none" type="submit"></button>
                        </div>
                    </div>
                </form>

                <div class="right_icons">
                    <a href="#">
                        <div class="sprite_camera_icon"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_compass_icon"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_heart_icon_outline"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_user_icon_outline"></div>
                    </a>
                    <a href="{% url 'account_logout' %}">
                        <div class="sprite_unlock_icon"></div>
                    </a>
                </div>
            </section>
        </header>
    </section>
{% else %}
    <header id="header">
        <section class="h_inner">
            <h1 class="logo">
                <div OnClick="location.href ='{% url 'account_login' %}'" style="cursor:pointer;" class="sprite_write_logo"></div>
            </h1>
        </section>
    </header>
{% endif %}


{% endblock header %}

post/templates/post_base/base_with_header.html
{% extends "post_base/base.html" %}
{% load static %}
{% block index-style %} {% endblock %}
{% block header %}

{% if user.is_authenticated %}
    <section id="container">
        <header id="header">
            <section class="inner">
                <h1 class="logo">
                    <a href="#">
                        <div class="sprite_write_logo"></div>
                    </a>
                </h1>
                <form action="#" method="get">
                    <div class="search_box">
                        <input name="query" type="text" placeholder="검색" id="search-field" >
                        <div class="fake_field">
                            <span class="sprite_small_search_icon"></span>
                            <span>검색</span>
                            <button style="display:none" type="submit"></button>
                        </div>
                    </div>
                </form>
                <div class="right_icons">
                    <a href="#">
                        <div class="sprite_camera_icon"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_compass_icon"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_heart_icon_outline"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_user_icon_outline"></div>
                    </a>
                    <a href="/account/logout">
                        <div class="sprite_unlock_icon"></div>
                    </a>
                </div>
            </section>
        </header>
    </section>
{% else %}
    <header id="header">
        <section class="h_inner">
            <h1 class="logo">
                <div OnClick="location.href ="/account/logout"" style="cursor:pointer;" class="sprite_write_logo"></div>
            </h1>
        </section>
    </header>
{% endif %}


{% endblock header %}

user/templates/user/account/login.html
{% extends "../user_base/base_with_header.html" %}

{% load static %}

{% block title %}로그인 | Sparkling Coffee Club{% endblock title %}

{% block content %}
    <div id="main_container">
        <div class="form_container ">
            <div class="form">
                <div class="title_cover">
                    <a href="#"><h1 class="sprite_insta_big_logo title"></h1></a>
                </div>
                <form method="post">{% csrf_token %}

                    <div>
                        <input name="username" type="text" placeholder="username">
                    </div>
                    <p>
                        <div>
                            <input name="password" type="password" placeholder="password">
                        </div>
                        <input type="submit" id="submit_btn" value="로그인" class="submit_btn">
                        <hr>                        
                        
                        <div class="password_reset_text">
                            <a href="#">
                                비밀번호를 잊으셨나요?</a>
                        </div>
                    </form>
                </div>
                <div class="bottom_box">
                    <div>
                        <span>계정이 없으신가요?</span>
                        <a class="sign_user_btn_color" href="{% url "user:signup"%}">가입하기</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

user/templates/user/account/signup.html
{% extends "../user_base/base_with_header.html" %}

{% load static %}

{% block title %}회원가입 | Sparkling Coffee Club{% endblock title %}

{% block content %}
    <div id="main_container">
        <div class="form_container">
            <div class="form">
                <div class="title_cover">
                    <a href="#">
                        <h1 class="sprite_insta_big_logo title"></h1>
                    </a>
                </div>
                <form method="post"  >{% csrf_token %}
                    <div class="sign_up_text">
                    친구들의 사진과 동영상을 보려면 가입하세요. 
                    </div>
                    <p>
                    <hr>
                    <div>
                        <input name="email" type="email" placeholder="email">
                    </div>
                    <p>
                    <div>
                        <input name="username" type="text" placeholder="username">
                    </div>
                    <p>
                    <div>
                        <input name="password" type="password" placeholder="password">
                    </div>
                    <p>
                    <div>
                        <input name="passwordcheck" type="password" placeholder="password check">
                    </div>
                    <p>
                    <input type="submit" id="submit_btn" value="가입" class="submit_btn">
                </form>
            </div>
            <div class="bottom_box">
                <div>
                    <span>계정이 있으신가요?</span>
                    <a class="sign_user_btn_color" href="{% url "user:signin"%}" >로그인</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user/templates/user/user_base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/styles/common.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'user/favicon/favicon.ico' %}">
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


    <title>{% block title %}Sparkling Coffee Club{% endblock title %}</title>
  </head>
  <body>
    {% block header %}{% endblock header %}
    {% block content %}{% endblock content %}
  </body>
</html>

user/templates/user/user_base/base_with_header.html
{% extends "../user_base/base.html" %}
{% load static %}

{% block header %}

{% if user.is_authenticated %}
    <section id="container">
        <header id="header">
            <section class="inner">
                <h1 class="logo">
                    <a href="#">
                        <div class="sprite_write_logo"></div>
                    </a>
                </h1>
                <div class="right_icons">
                    <a href="#">
                        <div class="sprite_camera_icon"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_compass_icon"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_heart_icon_outline"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_user_icon_outline"></div>
                    </a>
                    <a href="#">
                        <div class="sprite_unlock_icon"></div>
                    </a>
                </div>
            </section>
        </header>
    </section>
{% else %}
    <header id="header">
        <section class="h_inner">
            <h1 class="logo">
                <div OnClick="location.href ='#'" style="cursor:pointer;" class="sprite_write_logo"></div>
            </h1>
        </section>
    </header>
{% endif %}

{% endblock header %}